In [103]:
import pandas as pd

In [104]:
df = pd.read_csv('survey_results_public.csv', index_col='ResponseId')
schema_df = pd.read_csv('survey_results_schema.csv', index_col='qname')

In [105]:
pd.set_option('display.max_columns', 114)
pd.set_option('display.max_rows', 114)

In [106]:
df.head()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [107]:
df = pd.read_csv('sbi.csv')

In [108]:
df

,Date,series,OPEN,HIGH,LOW,PREV. CLOSE,ltp,close,vwap,52W H,52W L,VOLUME,VALUE,No of trades
0,20-Sep-2024,EQ,794.85,794.85,779.50,789.95,784.50,781.70,785.43,912.00,543.20,"2,13,72,244","16,78,63,88,691.70","2,65,805"
1,19-Sep-2024,EQ,795.05,801.35,784.05,792.75,791.50,789.95,791.39,912.00,543.20,"1,06,45,478","8,42,47,36,778.30","2,18,449"
2,18-Sep-2024,EQ,783.80,794.75,782.00,782.90,790.75,792.75,791.27,912.00,543.20,"1,83,24,412","14,49,95,92,000.20","2,55,355"
3,17-Sep-2024,EQ,785.60,787.50,780.55,785.55,782.75,782.90,784.12,912.00,543.20,"1,06,65,630","8,36,31,82,377.75","2,23,966"
4,16-Sep-2024,EQ,790.85,795.00,784.40,790.85,786.55,785.55,788.19,912.00,543.20,"95,53,736","7,53,01,68,486.30","2,35,580"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,28-Sep-2023,EQ,591.25,595.20,588.85,589.75,590.50,589.95,591.37,629.55,499.35,"2,19,60,816","12,98,69,61,371.85","2,87,488"
244,27-Sep-2023,EQ,593.45,594.30,588.20,594.40,590.00,589.75,590.74,629.55,499.35,"98,65,347","5,82,78,26,886.25","2,32,626"
245,26-Sep-2023,EQ,594.00,595.00,591.25,594.05,594.45,594.40,593.80,629.55,499.35,"83,27,427","4,94,48,09,375.45","1,85,873"
246,25-Sep-2023,EQ,601.50,601.50,590.45,598.15,593.95,594.05,594.79,629.55,499.35,"97,12,784","5,77,71,09,828.20","2,62,285"
247,22-Sep-2023,EQ,593.50,602.00,591.40,588.15,598.70,598.15,598.12,629.55,499.35,"1,87,84,139","11,23,52,13,845.05","2,95,166"

In [109]:
df.shape

(248, 14)

In [113]:
df.columns

Index(['date ', 'series ', 'open ', 'high ', 'low ', 'prev. close ', 'ltp ',
       'close ', 'vwap ', '52w h ', '52w l ', 'volume ', 'value ',
       'no of trades '],
      dtype='object')

In [112]:
df.columns = [x.lower() for x in df.columns]

In [115]:
df.columns = [x.strip() for x in df.columns]

In [117]:
df.loc[0, 'date']

'20-Sep-2024'

In [118]:
df.loc[0, 'date'].day_name()

AttributeError: 'str' object has no attribute 'day_name'

In [120]:
df['date'] = pd.to_datetime(df['date'], format='%d-%b-%Y')

In [121]:
df.loc[0, 'date'].day_name()

'Friday'

In [122]:
df['date'].dt.day_name()

0         Friday
1       Thursday
2      Wednesday
3        Tuesday
4         Monday
         ...
243     Thursday
244    Wednesday
245      Tuesday
246       Monday
247       Friday
Name: date, Length: 248, dtype: object

In [123]:
df['dayofweek'] = df['date'].dt.day_name()

In [124]:
df.head(5)

,date,series,open,high,low,prev. close,ltp,close,vwap,52w h,52w l,volume,value,no of trades,dayofweek
0,2024-09-20,EQ,794.85,794.85,779.50,789.95,784.50,781.70,785.43,912.0,543.2,"2,13,72,244","16,78,63,88,691.70","2,65,805",Friday
1,2024-09-19,EQ,795.05,801.35,784.05,792.75,791.50,789.95,791.39,912.0,543.2,"1,06,45,478","8,42,47,36,778.30","2,18,449",Thursday
2,2024-09-18,EQ,783.80,794.75,782.00,782.90,790.75,792.75,791.27,912.0,543.2,"1,83,24,412","14,49,95,92,000.20","2,55,355",Wednesday
3,2024-09-17,EQ,785.60,787.50,780.55,785.55,782.75,782.90,784.12,912.0,543.2,"1,06,65,630","8,36,31,82,377.75","2,23,966",Tuesday
4,2024-09-16,EQ,790.85,795.00,784.40,790.85,786.55,785.55,788.19,912.0,543.2,"95,53,736","7,53,01,68,486.30","2,35,580",Monday

In [125]:
df['date'].min()

Timestamp('2023-09-22 00:00:00')

In [126]:
df['date'].max()

Timestamp('2024-09-20 00:00:00')

In [127]:
df['date'].max() - df['date'].min()

Timedelta('364 days 00:00:00')

In [128]:
filt = df['date'] >= '2024'
df.loc[filt]

,date,series,open,high,low,prev. close,ltp,close,vwap,52w h,52w l,volume,value,no of trades,dayofweek
0,2024-09-20,EQ,794.85,794.85,779.50,789.95,784.50,781.70,785.43,912.0,543.20,"2,13,72,244","16,78,63,88,691.70","2,65,805",Friday
1,2024-09-19,EQ,795.05,801.35,784.05,792.75,791.50,789.95,791.39,912.0,543.20,"1,06,45,478","8,42,47,36,778.30","2,18,449",Thursday
2,2024-09-18,EQ,783.80,794.75,782.00,782.90,790.75,792.75,791.27,912.0,543.20,"1,83,24,412","14,49,95,92,000.20","2,55,355",Wednesday
3,2024-09-17,EQ,785.60,787.50,780.55,785.55,782.75,782.90,784.12,912.0,543.20,"1,06,65,630","8,36,31,82,377.75","2,23,966",Tuesday
4,2024-09-16,EQ,790.85,795.00,784.40,790.85,786.55,785.55,788.19,912.0,543.20,"95,53,736","7,53,01,68,486.30","2,35,580",Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,2024-01-05,EQ,645.00,651.75,637.75,642.75,641.45,641.95,645.02,660.4,499.35,"1,59,84,585","10,31,04,53,920.00","2,72,662",Friday
177,2024-01-04,EQ,642.50,646.40,638.65,643.45,643.60,642.75,642.95,660.4,499.35,"1,38,83,388","8,92,63,55,539.75","2,71,568",Thursday
178,2024-01-03,EQ,639.35,648.00,635.80,639.45,644.50,643.45,643.21,660.4,499.35,"1,45,71,772","9,37,27,32,858.90","2,52,225",Wednesday
179,2024-01-02,EQ,641.35,648.00,633.85,641.35,639.20,639.45,640.47,660.4,499.35,"1,51,64,482","9,71,23,46,967.95","2,49,803",Tuesday
180,2024-01-01,EQ,642.20,646.90,638.00,642.05,638.10,641.35,643.93,660.4,499.35,"82,95,548","5,34,17,16,373.30","2,57,804",Monday

In [130]:
df.set_index('date', inplace=True)

In [133]:
df = df.sort_index()
df.loc['2024-01': '2024-03']

,series,open,high,low,prev. close,ltp,close,vwap,52w h,52w l,volume,value,no of trades,dayofweek
date,,,,,,,,,,,,,,
2024-01-01,EQ,642.20,646.90,638.00,642.05,638.10,641.35,643.93,660.40,499.35,"82,95,548","5,34,17,16,373.30","2,57,804",Monday
2024-01-02,EQ,641.35,648.00,633.85,641.35,639.20,639.45,640.47,660.40,499.35,"1,51,64,482","9,71,23,46,967.95","2,49,803",Tuesday
2024-01-03,EQ,639.35,648.00,635.80,639.45,644.50,643.45,643.21,660.40,499.35,"1,45,71,772","9,37,27,32,858.90","2,52,225",Wednesday
2024-01-04,EQ,642.50,646.40,638.65,643.45,643.60,642.75,642.95,660.40,499.35,"1,38,83,388","8,92,63,55,539.75","2,71,568",Thursday
2024-01-05,EQ,645.00,651.75,637.75,642.75,641.45,641.95,645.02,660.40,499.35,"1,59,84,585","10,31,04,53,920.00","2,72,662",Friday
2024-01-08,EQ,640.00,645.00,625.05,641.95,627.90,627.00,633.49,660.40,499.35,"1,47,39,531","9,33,73,25,175.95","3,36,839",Monday
2024-01-09,EQ,632.00,634.35,624.50,627.00,625.95,625.40,629.70,660.40,499.35,"1,34,00,235","8,43,80,88,899.05","2,36,123",Tuesday
2024-01-10,EQ,624.80,625.30,618.20,625.40,622.00,621.75,622.15,660.40,499.35,"1,27,42,464","7,92,76,74,893.10","2,13,657",Wednesday
2024-01-11,EQ,626.00,627.15,618.50,621.75,621.25,620.20,621.85,660.40,499.35,"1,55,33,860","9,65,97,92,551.10","2,84,550",Thursday
2024-01-12,EQ,623.80,636.50,621.10,620.20,635.25,633.60,630.54,660.40,499.35,"1,66,20,797","10,48,01,04,627.65","3,02,558",Friday
2024-01-15,EQ,638.90,645.50,636.10,633.60,640.80,640.10,640.23,660.40,499.35,"1,68,44,018","10,78,40,99,571.95","3,00,031",Monday
2024-01-16,EQ,640.00,644.90,633.45,640.10,637.55,636.90,639.72,660.40,499.35,"1,50,25,543","9,61,21,87,789.45","2,53,396",Tuesday
2024-01-17,EQ,624.00,636.80,623.00,636.90,626.45,626.00,628.60,660.40,499.35,"3,00,16,308","18,86,83,96,654.85","4,28,458",Wednesday
2024-01-18,EQ,625.80,633.45,619.05,626.00,628.50,628.30,627.46,660.40,499.35,"1,46,95,436","9,22,07,94,332.40","2,39,183",Thursday
2024-01-19,EQ,633.00,635.50,624.70,628.30,628.70,627.75,629.47,660.40,499.35,"1,16,75,202","7,34,91,40,974.30","2,08,754",Friday
2024-01-20,EQ,629.00,633.80,624.10,627.75,631.00,631.40,628.99,660.40,499.35,"98,86,760","6,21,87,02,860.50","1,33,765",Saturday
2024-01-23,EQ,627.00,634.90,600.65,631.40,606.00,605.10,613.88,660.40,499.35,"3,09,54,343","19,00,24,05,937.25","4,09,569",Tuesday
2024-01-24,EQ,609.95,622.35,603.10,605.10,618.00,618.30,615.78,660.40,499.35,"1,92,21,835","11,83,64,60,488.35","2,74,606",Wednesday
2024-01-25,EQ,618.50,623.80,606.25,618.30,615.00,612.75,612.47,660.40,499.35,"2,26,84,904","13,89,39,36,068.05","2,95,756",Thursday
2024-01-29,EQ,619.00,629.50,615.60,612.75,624.20,622.95,622.28,660.40,499.35,"1,95,72,140","12,17,92,66,716.90","3,75,931",Monday
2024-01-30,EQ,625.45,633.50,624.20,622.95,625.50,626.75,628.36,660.40,499.35,"1,69,66,577","10,66,11,20,748.15","3,40,803",Tuesday
2024-01-31,EQ,626.40,643.20,622.00,626.75,641.55,640.50,634.65,660.40,499.35,"2,32,70,745","14,76,87,84,599.55","3,31,696",Wednesday
2024-02-01,EQ,642.75,652.95,633.25,640.50,648.50,647.65,644.85,660.40,499.35,"2,65,87,707","17,14,50,97,528.60","3,41,287",Thursday
2024-02-02,EQ,652.00,660.55,646.70,647.65,648.00,649.65,653.81,660.55,499.35,"2,74,71,811","17,96,12,31,828.75","3,62,306",Friday
2024-02-05,EQ,647.10,654.80,638.75,649.65,643.00,642.95,646.89,660.55,501.55,"2,83,39,525","18,33,25,81,475.65","3,48,687",Monday
2024-02-06,EQ,644.45,655.00,637.70,642.95,654.80,650.25,644.26,660.55,501.55,"1,40,79,390","9,07,07,37,392.70","2,30,842",Tuesday
2024-02-07,EQ,655.05,677.95,655.00,650.25,677.50,675.25,669.94,677.95,501.55,"4,16,96,232","27,93,40,60,703.15","7,97,692",Wednesday
2024-02-08,EQ,680.40,718.90,678.50,675.25,699.80,699.55,700.87,718.90,501.55,"7,42,22,434","52,02,06,33,464.10","9,78,644",Thursday
2024-02-09,EQ,703.65,728.35,694.20,699.55,725.45,725.25,711.47,728.35,501.55,"4,32,35,061","30,76,02,44,551.05","7,57,763",Friday
2024-02-12,EQ,726.00,726.00,704.50,725.25,707.00,707.90,713.27,728.35,501.55,"2,28,73,137","16,31,48,27,822.60","5,73,623",Monday
2024-02-13,EQ,708.55,718.00,702.15,707.90,711.35,713.45,711.68,728.35,501.55,"2,33,51,472","16,61,86,87,259.40","3,64,739",Tuesday
2024-02-14,EQ,705.55,748.50,705.55,713.45,743.00,743.40,730.54,748.50,501.55,"3,67,82,182","26,87,09,28,805.05","4,93,455",Wednesday
2024-02-15,EQ,747.70,764.00,741.65,743.40,760.40,761.70,754.14,764.00,501.55,"3,39,41,282","25,59,65,07,159.35","8,63,114",Thursday
2024-02-16,EQ,763.45,774.60,753.35,761.70,757.35,754.70,763.14,774.60,501.55,"2,73,65,121","20,88,33,78,535.90","5,19,358",Friday
2024-02-19,EQ,758.70,765.00,750.00,754.70,759.65,759.25,758.61,774.60,501.55,"1,39,79,584","10,60,50,31,489.65","2,53,774",Monday
2024-02-20,EQ,759.05,763.50,754.00,759.25,760.65,760.10,759.33,774.60,501.55,"1,25,28,399","9,51,31,87,763.75","2,60,985",Tuesday
2024-02-21,EQ,760.65,777.50,759.60,760.10,772.05,771.50,770.65,777.50,501.55,"2,14,65,311","16,54,22,28,829.40","4,41,746",Wednesday
2024-02-22,EQ,773.00,773.00,757.00,771.50,766.95,765.90,764.01,777.50,501.55,"1,87,99,244","14,36,28,48,260.80","3,72,278",Thursday
2024-02-23,EQ,765.90,770.50,755.00,765.90,760.35,759.05,761.81,777.50,501.55,"1,41,43,636","10,77,48,10,691.75","4,79,997",Friday
2024-02-26,EQ,755.00,766.35,752.70,759.05,758.40,758.90,759.32,777.50,501.55,"1,13,55,186","8,62,22,14,664.70","2,80,156",Monday
2024-02-27,EQ,758.90,762.35,742.20,758.90,749.50,749.85,751.69,777.50,501.55,"1,39,69,393","10,50,06,29,239.15","3,15,352",Tuesday
2024-02-28,EQ,749.85,756.75,741.00,749.85,743.00,742.50,747.76,777.50,501.55,"1,12,63,318","8,42,22,54,972.85","2,83,338",Wednesday
2024-02-29,EQ,743.90,753.90,737.15,742.50,753.00,748.10,745.74,777.50,501.55,"1,92,17,113","14,33,08,98,842.35","3,89,495",Thursday
2024-03-01,EQ,752.00,772.00,751.95,748.10,770.00,769.15,763.20,777.50,501.55,"1,73,48,526","13,24,04,13,220.45","3,09,262",Friday
2024-03-02,EQ,771.95,777.00,768.90,769.15,773.70,773.30,774.03,777.50,501.55,"11,58,960","89,70,65,444.75","27,382",Saturday
2024-03-04,EQ,774.40,777.00,769.00,773.30,771.35,772.05,772.72,777.50,501.55,"97,89,141","7,56,42,84,699.60","1,97,362",Monday
2024-03-05,EQ,769.50,786.95,769.10,772.05,784.60,783.95,782.20,786.95,501.55,"1,80,88,847","14,14,91,13,322.65","4,04,509",Tuesday
2024-03-06,EQ,783.65,790.30,772.90,783.95,783.70,783.90,783.81,790.30,501.55,"2,67,10,525","20,93,60,92,585.05","5,03,262",Wednesday
2024-03-07,EQ,790.00,793.40,783.00,783.90,786.00,788.05,788.54,793.40,501.55,"1,54,97,868","12,22,07,05,592.60","2,19,629",Thursday
2024-03-11,EQ,790.00,792.80,770.55,788.05,773.95,773.70,778.59,793.40,501.55,"1,67,78,340","13,06,34,54,668.35","3,87,291",Monday
2024-03-12,EQ,770.00,777.75,757.35,773.70,759.00,759.70,764.67,793.40,501.55,"2,15,29,705","16,46,30,45,923.05","3,90,497",Tuesday
2024-03-13,EQ,758.65,763.70,743.00,759.70,747.40,747.25,751.85,793.40,501.55,"2,79,50,252","21,01,43,17,799.65","4,62,302",Wednesday
2024-03-14,EQ,749.90,750.80,734.05,747.25,741.00,741.05,743.03,793.40,501.55,"1,97,30,882","14,66,06,90,669.70","3,04,735",Thursday
2024-03-15,EQ,739.25,746.55,723.00,741.05,732.65,731.90,731.27,793.40,501.55,"2,97,92,241","21,78,60,99,985.35","3,82,516",Friday
2024-03-18,EQ,727.10,737.90,722.10,731.90,732.45,730.95,729.81,793.40,501.55,"1,81,45,126","13,24,25,20,782.95","2,66,091",Monday
2024-03-19,EQ,730.00,734.35,721.15,730.95,722.55,723.80,727.47,793.40,501.55,"1,52,05,043","11,06,12,61,059.95","2,03,852",Tuesday
2024-03-20,EQ,725.15,738.95,719.80,723.80,736.60,736.25,731.17,793.40,501.55,"2,54,05,455","18,57,56,65,608.10","4,11,626",Wednesday
2024-03-21,EQ,742.00,750.60,740.55,736.25,742.80,744.30,745.38,793.40,501.55,"1,51,61,161","11,30,08,17,864.00","2,97,397",Thursday
2024-03-22,EQ,743.85,748.80,741.40,744.30,746.50,746.70,746.09,793.40,501.55,"1,55,35,921","11,59,11,96,217.50","2,61,750",Friday
2024-03-26,EQ,743.05,747.85,738.50,746.70,741.80,740.05,741.15,793.40,501.55,"1,46,78,342","10,87,88,01,267.10","4,71,853",Tuesday
2024-03-27,EQ,743.00,745.85,730.20,740.05,736.50,733.30,735.91,793.40,501.55,"3,00,88,789","22,14,26,32,347.65","3,03,834",Wednesday
2024-03-28,EQ,737.75,759.55,736.90,733.30,752.95,752.35,750.83,793.40,501.55,"2,17,05,116","16,29,67,64,834.75","2,50,615",Thursday

In [134]:
df.loc['2024-01': '2024-03']['high'].max()

np.float64(793.4)

In [135]:
df.loc['2024-01': '2024-03']['low'].min()

np.float64(600.65)

In [136]:
df.loc['2024-01': '2024-03']['high'].mean()

np.float64(707.8564516129032)

In [137]:
df['high'].resample('W')

In [139]:
df['high'].resample('W').min()

date
2023-09-24    602.00
2023-10-01    594.30
2023-10-08    594.35
2023-10-15    581.30
2023-10-22    570.00
2023-10-29    552.90
2023-11-05    566.70
2023-11-12    581.00
2023-11-19    574.50
2023-11-26    562.45
2023-12-03    565.20
2023-12-10    596.00
2023-12-17    617.95
2023-12-24    648.95
2023-12-31    641.30
2024-01-07    646.40
2024-01-14    625.30
2024-01-21    633.45
2024-01-28    622.35
2024-02-04    629.50
2024-02-11    654.80
2024-02-18    718.00
2024-02-25    763.50
2024-03-03    753.90
2024-03-10    777.00
2024-03-17    746.55
2024-03-24    734.35
2024-03-31    745.85
2024-04-07    761.50
2024-04-14    770.00
2024-04-21    752.00
2024-04-28    769.00
2024-05-05    831.25
2024-05-12    814.65
2024-05-19    819.85
2024-05-26    826.65
2024-06-02    834.45
2024-06-09    795.00
2024-06-16    839.60
2024-06-23    848.05
2024-06-30    836.00
2024-07-07    843.85
2024-07-14    858.30
2024-07-21    887.35
2024-07-28    850.75
2024-08-04    858.30
2024-08-11    810.70
2024-08-18    809.15
2024-08-25    821.00
2024-09-01    816.00
2024-09-08    812.90
2024-09-15    788.00
2024-09-22    787.50
Freq: W-SUN, Name: high, dtype: float64

In [140]:
highs = df['high'].resample('W').max()

In [141]:
highs.loc['2024-07-07']

np.float64(861.25)

In [142]:
df.columns

Index(['series', 'open', 'high', 'low', 'prev. close', 'ltp', 'close', 'vwap',
       '52w h', '52w l', 'volume', 'value', 'no of trades', 'dayofweek'],
      dtype='object')

In [143]:
df.resample('W').agg({'high': 'max', 'low': 'min', 'volume': 'sum'})

              high     low                                             volume
date
2023-09-24  602.00  591.40                                        1,87,84,139
2023-10-01  601.50  588.20  97,12,78483,27,42798,65,3472,19,60,8161,21,89,735
2023-10-08  604.90  584.45         1,53,22,1962,49,14,6121,32,48,02882,16,780
2023-10-15  597.00  574.80  91,89,5971,03,73,5081,42,20,1191,19,83,7971,90...
2023-10-22  579.95  562.10  1,12,90,2931,07,65,2241,17,77,4541,14,41,4991,...
2023-10-29  566.00  543.20       1,18,75,0351,21,34,6241,94,24,8251,04,15,296
2023-11-05  579.50  556.50  85,93,7041,30,39,6961,35,75,5751,11,48,5161,13...
2023-11-12  584.75  572.60  1,64,99,1381,79,23,2811,54,34,8081,24,34,36367...
2023-11-19  588.00  562.10         1,12,82,3621,13,97,67686,22,6603,71,73,221
2023-11-26  566.80  555.15  1,27,14,5851,42,80,0131,49,09,07163,76,21065,2...
2023-12-03  574.20  561.10         81,53,3141,02,99,0341,97,58,9981,06,14,230
2023-12-10  616.80  584.55  2,60,77,8823,64,30,1522,14,39,0691,07,25,7061,...
2023-12-17  650.00  610.80  1,17,06,2551,44,94,8361,39,77,9141,58,13,7972,...
2023-12-24  660.40  627.50  1,62,21,7961,99,64,0082,25,42,0561,99,15,5161,...
2023-12-31  653.30  635.65       1,01,53,0891,44,17,6461,69,82,0921,32,21,898
2024-01-07  651.75  633.85  82,95,5481,51,64,4821,45,71,7721,38,83,3881,59...
2024-01-14  645.00  618.20  1,47,39,5311,34,00,2351,27,42,4641,55,33,8601,...
2024-01-21  645.50  619.05  1,68,44,0181,50,25,5433,00,16,3081,46,95,4361,...
2024-01-28  634.90  600.65                  3,09,54,3431,92,21,8352,26,84,904
2024-02-04  660.55  615.60  1,95,72,1401,69,66,5772,32,70,7452,65,87,7072,...
2024-02-11  728.35  637.70  2,83,39,5251,40,79,3904,16,96,2327,42,22,4344,...
2024-02-18  774.60  702.15  2,28,73,1372,33,51,4723,67,82,1823,39,41,2822,...
2024-02-25  777.50  750.00  1,39,79,5841,25,28,3992,14,65,3111,87,99,2441,...
2024-03-03  777.00  737.15  1,13,55,1861,39,69,3931,12,63,3181,92,17,1131,...
2024-03-10  793.40  769.00         97,89,1411,80,88,8472,67,10,5251,54,97,868
2024-03-17  792.80  723.00  1,67,78,3402,15,29,7052,79,50,2521,97,30,8822,...
2024-03-24  750.60  719.80  1,81,45,1261,52,05,0432,54,05,4551,51,61,1611,...
2024-03-31  759.55  730.20                  1,46,78,3423,00,88,7892,17,05,116
2024-04-07  775.30  752.10  99,49,9711,57,13,0631,91,36,9811,58,89,53099,3...
2024-04-14  780.70  761.10           97,97,17474,65,8921,45,30,6691,44,08,722
2024-04-21  763.30  732.05       1,13,56,5721,33,38,9911,45,89,6481,08,86,554
2024-04-28  816.90  750.45  1,74,52,1861,22,92,42978,42,6153,67,32,9741,49...
2024-05-05  836.20  798.70       2,73,02,7322,74,49,0731,99,43,7242,26,67,634
2024-05-12  839.65  793.20  3,52,83,5571,67,25,0132,79,08,3224,92,90,2542,...
2024-05-19  826.15  797.35  1,53,98,5051,09,12,46297,55,0622,05,36,9901,24...
2024-05-26  841.25  813.55       1,40,37,8011,92,39,2771,74,97,4881,22,52,075
2024-06-02  840.70  817.10  1,22,95,1931,38,18,8931,45,18,2321,78,18,7052,...
2024-06-09  912.00  731.95  6,42,69,02012,23,81,1937,42,56,0824,05,55,6492...
2024-06-16  849.90  829.05  1,67,25,5081,47,54,4081,50,71,4421,25,23,9721,...
2024-06-23  860.60  828.60       1,49,29,0833,29,25,1401,39,85,3521,89,90,090
2024-06-30  864.00  821.05  1,27,15,2542,09,17,5301,62,81,7602,03,78,8872,...
2024-07-07  861.25  823.15  1,09,67,7972,11,42,8402,35,98,0091,33,72,5872,...
2024-07-14  869.95  843.50  1,03,59,8001,35,85,0811,73,43,23685,01,3661,14...
2024-07-21  899.00  859.70       2,53,92,8201,18,93,6921,94,35,1831,45,62,742
2024-07-28  895.00  841.20  1,46,14,1111,82,79,2121,96,24,84595,22,3751,20...
2024-08-04  889.10  846.15  2,65,82,7811,35,28,4471,16,36,8741,17,87,2031,...
2024-08-11  831.35  795.65  2,76,76,9511,79,00,9301,76,92,3551,47,69,0691,...
2024-08-18  823.00  795.05       1,61,20,4491,75,85,1721,17,88,6651,14,27,335
2024-08-25  825.40  811.20  1,01,51,4821,03,47,4931,46,07,25778,32,91755,3...
2024-09-01  823.45  806.50  85,23,7951,28,33,2901,03,71,3001,82,47,26889,1...
2024-09-08  825.95  777.00  1,18,13,7501,05,48,3501,07,89,57083,95,0744,02...
2024-09-15  795.00  765.40  2,13,22,1031,28,24,7012,00,60,6651,75,78,9641,...
2024-09-22  801.35  779.50  95,53,7361,06,65,6301,83,24,4121,06,45,4782,13...